/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2020-03-03 07:23:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cssnotes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<body>\n");
      out.write("<img src=\"noteslogo.png\" align=\"top\" width=\"300\" height=\"100\">\n");
      out.write("<img src=\"notes.jpg\" width=\"150\" height=\"100\">\n");
      out.write("<img src=\"remember.jpg\" align=\"top\" width=\"300\" height=\"100\">\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<hr color=DeepSkyBlue>\n");
      out.write("<hr color=blue>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".sub a{\n");
      out.write("\tcolor:#fff;\n");
      out.write("\tbackground:#272727;\n");
      out.write("\ttext-decoration:none;\n");
      out.write("\tpadding:10px 20px;\n");
      out.write("\tfont-size:13px;\n");
      out.write("\tfont-family: arial, serif;\n");
      out.write("\tfont-weight:bold;\n");
      out.write("\t-webkit-border-radius:.5em;\n");
      out.write("\t-moz-border-radius:.5em;\n");
      out.write("\t-border-radius:.5em;\n");
      out.write("}\n");
      out.write("*{\n");
      out.write("padding:0px;\n");
      out.write("margin:0px;\n");
      out.write("}\n");
      out.write("div{\n");
      out.write("width:250px;\n");
      out.write("height:666px;\n");
      out.write("background:#1A8DA9;\n");
      out.write("}\n");
      out.write("div a{\n");
      out.write("text-decoration:none;\n");
      out.write("color:white;\n");
      out.write("padding:20px;\n");
      out.write("padding-right:100px;\n");
      out.write("}\n");
      out.write("div ul li{\n");
      out.write("list-style-type:none;\n");
      out.write("display:block;\n");
      out.write("padding:15px;\n");
      out.write("border-bottom:2px solid #236D7F;\n");
      out.write("}\n");
      out.write("div ul li:hover{\n");
      out.write("background:white;\n");
      out.write("transition:linear all 0.40s;\n");
      out.write("margin-left:10px\n");
      out.write("}\n");
      out.write("div ul li a:hover{\n");
      out.write("color:black;\n");
      out.write("}\n");
      out.write(".selected{\n");
      out.write("background:white;\n");
      out.write("}\n");
      out.write(".selected a{\n");
      out.write("color:black;\n");
      out.write("}\n");
      out.write(".navmenu{\n");
      out.write("float:left;\n");
      out.write("}\n");
      out.write("p{\n");
      out.write("margin-left:320px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Notes</title>\n");
      out.write("<body>\n");
      out.write("<div class=\"navmenu\">\n");
      out.write("<nav>\n");
      out.write(" <ul>\n");
      out.write(" <li ><a href=\"home1.jsp\"><b>HOME</b></a></li>\n");
      out.write(" <li ><a href=\"notes.jsp\">Introduction</a></li>\n");
      out.write("\n");
      out.write("<li><a href=\"cnotes.jsp\"><b>C-</b>Notes</a></li>\n");
      out.write("<li><a href=\"c++notes.jsp\"><b>C++-</b>Notes</a></li>\n");
      out.write("<li><a href=\"javanotes.jsp\"><b>JAVA-</b>Notes</a></li>\n");
      out.write("<li><a href=\"htmlnotes.jsp\"><b>HTML-</b>Notes</a></li>\n");
      out.write("<li class=\"selected\"><a href=\"#\"><b>CSS-</b> Notes</a></li>\n");
      out.write("<li ><a href=\"Login.html\"><b>Logout</b></a></li>\n");
      out.write("<li ><a href=\"aboutus.html\"><b>About Us</b></a></li>\n");
      out.write("<li ><a href=\"contactus.html\"><b>Contact Us</b></a></li>\n");
      out.write("\n");
      out.write("</ul>\n");
      out.write("</nav>\n");
      out.write("</div>\n");
      out.write("<h2>Introduction To CSS</h2><br>\n");
      out.write("<p>A CSS (cascading style sheet) file allows you to separate your web sites (X)HTML content from it&#8217;s style. As always you use your (X)HTML file to arrange the content, but all of the presentation (fonts, colors, background, borders, text formatting, link effects &amp; so on&#8230;) are accomplished within a CSS.</p>\n");
      out.write("<p>At this point you have some choices of how to use the CSS, either internally or externally.</p>\n");
      out.write("<br>\n");
      out.write("<h2>Internal Stylesheet</h2><br>\n");
      out.write("<p>First we will explore the internal method. This way you are simply placing the CSS code within the &lt;head&gt;&lt;/head&gt; tags of each (X)HTML file you want to style with the CSS. The format for this is shown in the example below.</p>\n");
      out.write("<p >&lt;head&gt;<br />\n");
      out.write("&lt;title&gt;&lt;title&gt;<br />\n");
      out.write("&lt;style type=&#8221;text/css&#8221;&gt;<br />\n");
      out.write("<em><span class=\"paths\">CSS Content Goes Here</span></em><br />\n");
      out.write("&lt;/style&gt;<br />\n");
      out.write("&lt;/head&gt;<br />\n");
      out.write("&lt;body&gt;</p>\n");
      out.write("<p>With this method each (X)HTML file contains the CSS code needed to style the page. Meaning that any changes you want to make to one page, will have to be made to all. This method can be good if you need to style only one page, or if you want different pages to have varying styles.</p>\n");
      out.write("<br>\n");
      out.write("<h2>External Stylesheet</h2><br>\n");
      out.write("<p>Next we will explore the external method. An external CSS file can be created with any text or HTML editor such as &#8220;Notepad&#8221; or &#8220;Dreamweaver&#8221;. A CSS file contains no (X)HTML, only CSS. You simply save it with the .css file extension. You can link to the file externally by placing one of the following links in the head section of every (X)HTML file you want to style with the CSS file.</p>\n");
      out.write("<p >&lt;link rel=&#8221;stylesheet&#8221; type=&#8221;text/css&#8221; href=<em><span>&#8220;Path To stylesheet.css&#8221;</span></em> /&gt;</p>\n");
      out.write("<p>Or you can also use the @import method as shown below</p>\n");
      out.write("<p >&lt;style type=&#8221;text/css&#8221;&gt;@import url(<em><span class=\"paths\">Path To stylesheet.css</span></em>)&lt;/style&gt;</p>\n");
      out.write("<p>Either of these methods are achieved by placing one or the other in the head section as shown in example below.</p>\n");
      out.write("<p >&lt;head&gt;<br />\n");
      out.write("&lt;title&gt;&lt;title&gt;<br />\n");
      out.write("<em><span>&lt;link rel=&#8221;stylesheet&#8221; type=&#8221;text/css&#8221;href=&#8221;style.css&#8221; /&gt;</span></em><br />\n");
      out.write("&lt;/head&gt;<br />\n");
      out.write("&lt;body&gt;</p>\n");
      out.write("<p>or</p>\n");
      out.write("<p>&lt;head&gt;<br />\n");
      out.write("&lt;title&gt;&lt;title&gt;<br />\n");
      out.write("&lt;style type=&#8221;text/css&#8221;&gt; <em><span >@import url(<em><span>Path To stylesheet.css</span></em>)</span></em> &lt;/style&gt;<br />\n");
      out.write("&lt;/head&gt;<br />\n");
      out.write("&lt;body&gt;</p>\n");
      out.write("<p>By using an external style sheet, all of your (X)HTML files link to one CSS file in order to style the pages. This means, that if you need to alter the design of all your pages, you only need to edit one .css file to make global changes to your entire website.</p>\n");
      out.write("<p>Here are a few reasons this is better.</p>\n");
      out.write("<br>\n");
      out.write("<p>Easier Maintenance</p>\n");
      out.write("<p>Reduced File Size</p>\n");
      out.write("<p>Reduced Bandwidth</p>\n");
      out.write("<p>Improved Flexibility</p>\n");
      out.write("<br>\n");
      out.write(" <br><h3 align=\"center\"><font color=\"blue\">To get complete notes on CSS click Download button</font></h3>\n");
      out.write("  <br>\n");
      out.write("  \n");
      out.write("\t<h3 align=\"center\" class=\"sub\"><a href=\"notes/html_tutorial.pdf\" target=\"_blank\">Download</a></h3>\n");
      out.write("  </body>\n");
      out.write(" </html>\n");
      out.write("   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
