/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2020-03-01 12:12:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class helloworld_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Hello world</title>\n");
      out.write("<body>\n");
      out.write("<img src=\"programing-world.jpg\" width=\"380\" height=\"80\">\n");
      out.write("<marquee width=\"900px\" direction=\"right\"><img src=\"globe.jpg\" width=\"100\" height=\"80\"></marquee>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".margin{\n");
      out.write("margin:100px;\n");
      out.write("}\n");
      out.write("ul {\n");
      out.write("    list-style-type: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    overflow: hidden;\n");
      out.write("    background-color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("    float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a, .drop {\n");
      out.write("    display: inline-block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 14px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("li a, .drop {\n");
      out.write("    display: inline-block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 14px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover, .dropdown:hover .dropbtn {\n");
      out.write("    background-color: red;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li.dropdown {\n");
      out.write("    display: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".drop-content {\n");
      out.write("    display: none;\n");
      out.write("    position: absolute;\n");
      out.write("    background-color: #f9f9f9;\n");
      out.write("    min-width: 160px;\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content {\n");
      out.write("    display: none;\n");
      out.write("    position: absolute;\n");
      out.write("    background-color: #f9f9f9;\n");
      out.write("    min-width: 160px;\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content a {\n");
      out.write("    color: black;\n");
      out.write("    padding: 12px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("    display: block;\n");
      out.write("    text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content a:hover {background-color: #f1f1f1}\n");
      out.write("\n");
      out.write(".dropdown:hover .dropdown-content {\n");
      out.write("    display: block;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("  .gallery-text{\n");
      out.write("  float:left;\n");
      out.write("  width:48%;\n");
      out.write("  margin:1%;\n");
      out.write("  }\n");
      out.write("  .gallery-text p{\n");
      out.write("  word-break:break-all;\n");
      out.write("  }\n");
      out.write(" \n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<ul>\n");
      out.write("  <li><a href=\"home1.jsp\">Home</a></li>\n");
      out.write(" <li class=\"dropdown\">\n");
      out.write("    <a href=\"tutorials.jsp\" class=\"dropc\">Tutorials</a>\n");
      out.write("   \n");
      out.write(" \n");
      out.write("  <li class=\"dropdown\">\n");
      out.write("    <a href=\"notes.jsp\" class=\"dropb\">Notes</a>\n");
      out.write("   \n");
      out.write("      <li class=\"dropdown\">\n");
      out.write("     <a href=\"javascript:void(0)\" class=\"dropa\">Sample Programs</a>\n");
      out.write("    <div class=\"dropdown-content\">\n");
      out.write("       <a href=\"csamples.html\">C</a>\n");
      out.write("      <a href=\"c++samples.html \">C++</a>\n");
      out.write("      <a href=\"javasamples.html\">JAVA</a>\n");
      out.write("    </div>\n");
      out.write("     <li><a href=\"helloworld.jsp\">Hello world</a></li>\n");
      out.write("     <li><a href=\"Prog-sites.html\">Top programming site</a></li>\n");
      out.write("     <li><a href=\"choosetest.html\">Take Test</a></li>\n");
      out.write("    <li><a href=\"aboutus.html\">About us</a></li>\n");
      out.write("     <li><a href=\"contactus.html\">Contact us</a></li>\n");
      out.write("     <li><a href=\"feedback.html\">Give Feedback</a></li>\n");
      out.write("          <li class=\"dropdown\">\n");
      out.write("     <a href=\"javascript:void(0)\" class=\"dropa\">Settings</a>\n");
      out.write("    <div class=\"dropdown-content\">\n");
      out.write("     <a href=\"changepassword.html\">Change Password</a>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("     <li><a href=\"Login.html\">Logout</a></li>\n");
      out.write("  </ul><br></br>\n");
      out.write("  \n");
      out.write("  <h1 style=\"color:blue;\">\"Hello, World!\" program</h1>\n");
      out.write("  <pre style=\"font-size:150%;\"><font face=\"sans-serif\">\n");
      out.write("  A<b>\"Hello, World!\"</b> program is a computer program that outputs or displays \"Hello, World!\" to the user.\n");
      out.write("  Being a very simple program in most programming languages,it is often used to illustrate the \n");
      out.write("  basic syntax of a programming language for a working program.It is often the very first program \n");
      out.write("  write when they are new to the language.\n");
      out.write("</font>\n");
      out.write("</pre>\n");
      out.write("<div id=\"gallery-text\">\n");
      out.write("<div class=\"gallery-text\">\n");
      out.write(" <h2><u>Hello world in different programming languages</u></h2>\n");
      out.write("\n");
      out.write("<div class=\"margin\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<h2>1.&nbsp;Bash</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("echo &quot;Hello World&quot;</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>2. Basic</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("PRINT &quot;Hello, world!&quot;â</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>3. C</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("#include <stdio.h>\n");
      out.write("&nbsp;\n");
      out.write("int main(void)\n");
      out.write("{\n");
      out.write("&nbsp; &nbsp; puts(&quot;Hello, world!&quot;);\n");
      out.write("}</stdio.h></pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>4. C++</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("#include <iostream>\n");
      out.write("&nbsp;\n");
      out.write("int main()\n");
      out.write("{\n");
      out.write("&nbsp; &nbsp; std::cout &lt;&lt; &quot;Hello, world!\n");
      out.write("&quot;;\n");
      out.write("&nbsp; &nbsp; return 0;\n");
      out.write("}</iostream></pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>5. C#</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("using System;\n");
      out.write("class Program\n");
      out.write("{\n");
      out.write("&nbsp; &nbsp; public static void Main(string[] args)\n");
      out.write("&nbsp; &nbsp; {\n");
      out.write("&nbsp; &nbsp; &nbsp; &nbsp; Console.WriteLine(&quot;Hello, world!&quot;);\n");
      out.write("&nbsp; &nbsp; }\n");
      out.write("}</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>6. Clipper</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("? &quot;Hello World&quot;</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>7. CoffeeScript</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("console.log &#39;Hello, world!&#39;</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>8. Delphi</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("program HelloWorld;\n");
      out.write("begin\n");
      out.write("&nbsp; Writeln(&#39;Hello, world!&#39;);\n");
      out.write("end.</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>9. HTML</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("\n");
      out.write("&nbsp;Hello World!</pre>\n");
      out.write("\n");
      out.write("<h2>&nbsp;</h2>\n");
      out.write("\n");
      out.write("<h2>10. Java</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("import javax.swing.JFrame; &nbsp;//Importing class JFrame\n");
      out.write("import javax.swing.JLabel; &nbsp;//Importing class JLabel\n");
      out.write("public class HelloWorld {\n");
      out.write("&nbsp;&nbsp; &nbsp;public static void main(String[] args) {\n");
      out.write("&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;JFrame frame = new JFrame(); &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //Creating frame\n");
      out.write("&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;frame.setTitle(&quot;Hi!&quot;); &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //Setting title frame\n");
      out.write("&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;frame.add(new JLabel(&quot;Hello, world!&quot;));//Adding text to frame\n");
      out.write("&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;frame.pack(); &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;//Setting size to smallest\n");
      out.write("&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;frame.setLocationRelativeTo(null); &nbsp; &nbsp; //Centering frame\n");
      out.write("&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;frame.setVisible(true); &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;//Showing frame\n");
      out.write("&nbsp;&nbsp; &nbsp;}\n");
      out.write("}</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>11. JavaScript</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("document.write(&#39;Hello, world!&#39;);</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>12. jQuery</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("$(&quot;body&quot;).append(&quot;Hello world!&quot;);\n");
      out.write("</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>13. Julia</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("println(&quot;Hello world!&quot;)</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>14. Logo</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("print [Hello, world!]</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>15. MatLab</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("disp(&#39;Hello, world!&#39;)</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>16. Objective-C</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("#import <stdio.h>\n");
      out.write("#import <foundation foundation.h=\"\">\n");
      out.write("&nbsp;\n");
      out.write("int main(void)\n");
      out.write("{\n");
      out.write("&nbsp; &nbsp; NSLog(@&quot;Hello, world!\n");
      out.write("&quot;);\n");
      out.write("&nbsp; &nbsp; return 0;\n");
      out.write("}</foundation></stdio.h></pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>17. Pascal</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("program HelloWorld;\n");
      out.write("begin\n");
      out.write("&nbsp; WriteLn(&#39;Hello, world!&#39;);\n");
      out.write("end.</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>18. Perl 5</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("print &quot;Hello, world!\n");
      out.write("&quot;;</pre>\n");
      out.write("\n");
      out.write("<p style=\"line-height: 20.7999992370605px;\">&nbsp;</p>\n");
      out.write("\n");
      out.write("<h2>19. PHP</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; line-height: 20.7999992370605px; background-color: rgb(244, 244, 244);\">\n");
      out.write("\n");
      out.write("  echo \"Hello World!\";\n");
      out.write("  echo \"PHP is so easy!\";\n");
      out.write("\n");
      out.write("&nbsp;</pre>\n");
      out.write("\n");
      out.write("<div style=\"line-height: 20.7999992370605px;\">&nbsp;</div>\n");
      out.write("\n");
      out.write("<div style=\"line-height: 20.7999992370605px;\">\n");
      out.write("<h2>20. Processing</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; background-color: rgb(244, 244, 244);\">\n");
      out.write("void setup(){\n");
      out.write("&nbsp; println(&quot;Hello, world!&quot;);\n");
      out.write("}</pre>\n");
      out.write("\n");
      out.write("<div>&nbsp;</div>\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<h2>21. Python</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; background-color: rgb(244, 244, 244);\">\n");
      out.write("print &quot;Hello, world!&quot;</pre>\n");
      out.write("\n");
      out.write("<div>&nbsp;</div>\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<h2>22. R</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; background-color: rgb(244, 244, 244);\">\n");
      out.write("cat(&#39;Hello, world!\n");
      out.write("&#39;)</pre>\n");
      out.write("\n");
      out.write("<div>&nbsp;</div>\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<h2>23. Ruby</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; background-color: rgb(244, 244, 244);\">\n");
      out.write("puts &quot;Hello, world!&quot;</pre>\n");
      out.write("\n");
      out.write("<div>&nbsp;</div>\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<h2>24. Swift</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; background-color: rgb(244, 244, 244);\">\n");
      out.write("println(&quot;Hello, world!&quot;)</pre>\n");
      out.write("\n");
      out.write("<div>&nbsp;</div>\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<h2>25. VBScript</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; background-color: rgb(244, 244, 244);\">\n");
      out.write("MsgBox &quot;Hello, World!&quot;</pre>\n");
      out.write("\n");
      out.write("<div>&nbsp;</div>\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<h2>26. Visual Basic .NET</h2>\n");
      out.write("\n");
      out.write("<pre style=\"padding: 10px; overflow: hidden; border: none; background-color: rgb(244, 244, 244);\">\n");
      out.write("Module Module1\n");
      out.write("&nbsp; &nbsp; Sub Main()\n");
      out.write("&nbsp; &nbsp; &nbsp; &nbsp; Console.WriteLine(&quot;Hello, world!&quot;)\n");
      out.write("&nbsp; &nbsp; End Sub\n");
      out.write("End Module</pre>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
