/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2020-03-01 12:08:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Home</title>\n");
      out.write("<body  onLoad=\"quotes_authors()\">\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function quotes_authors()\n");
      out.write("{\n");
      out.write("\tvar authors=new Array()\n");
      out.write("\tauthors[0]=\"Ralph Jhonson\";\n");
      out.write("\tauthors[1]=\"Doug Linder\";\n");
      out.write("\tauthors[2]=\"Edsger Dijkstra\";\n");
      out.write("\tauthors[3]=\"Jhon Jhonson\";\n");
      out.write("\tauthors[4]=\"Tom Van Vleck\";\n");
      out.write("\tauthors[5]=\"Donald Knuth\";\n");
      out.write("\n");
      out.write("\tvar quotes=new Array()\n");
      out.write("\tquotes[0]=\"Before software can be reusable it first has to be usable.\";\n");
      out.write("\tquotes[1]=\"A good programmer is someone who always looks both ways before crossing a one-way street.\";\n");
      out.write("\tquotes[2]=\"If debugging is the process of removing software bugs, then programming must be the process of putting them in.\";\n");
      out.write("\tquotes[3]=\"First, solve the problem. Then, write code\";\n");
      out.write("\tquotes[4]=\"Real Programmers dont comment their codes..!! Because if it was hard to write..It must be hard to read..!!\";\n");
      out.write("\tquotes[5]=\"Computers are good at following instructions, but not at reading your mind.\";\n");
      out.write("\n");
      out.write("\tindex=Math.floor(Math.random() * quotes.length);\n");
      out.write("\t\n");
      out.write("\talert(quotes[index]+\"    -\"+authors[index]);\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<img src=\"programing-world.jpg\" width=\"380\" height=\"80\">\n");
      out.write("<marquee width=\"900px\" direction=\"right\"><img src=\"globe.jpg\" width=\"100\" height=\"80\"></marquee>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("ul {\n");
      out.write("    list-style-type: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    overflow: hidden;\n");
      out.write("    background-color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("    float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a, .drop {\n");
      out.write("    display: inline-block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 14px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("li a, .drop {\n");
      out.write("    display: inline-block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 14px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover, .dropdown:hover .dropbtn {\n");
      out.write("    background-color: red;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li.dropdown {\n");
      out.write("    display: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".drop-content {\n");
      out.write("    display: none;\n");
      out.write("    position: absolute;\n");
      out.write("    background-color: #f9f9f9;\n");
      out.write("    min-width: 160px;\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content {\n");
      out.write("    display: none;\n");
      out.write("    position: absolute;\n");
      out.write("    background-color: #f9f9f9;\n");
      out.write("    min-width: 160px;\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content a {\n");
      out.write("    color: black;\n");
      out.write("    padding: 12px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("    display: block;\n");
      out.write("    text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content a:hover {background-color: #f1f1f1}\n");
      out.write("\n");
      out.write(".dropdown:hover .dropdown-content {\n");
      out.write("    display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body >\n");
      out.write("<ul>\n");
      out.write("  <li><a href=\"home1.jsp\">Home</a></li>\n");
      out.write(" <li class=\"dropdown\">\n");
      out.write(" <li>   <a href=\"tutorials.jsp\" class=\"dropc\">Tutorials</a></li>\n");
      out.write("<li class=\"dropdown\">\n");
      out.write("    <a href=\"notes.jsp\" class=\"dropb\">Notes</a>\n");
      out.write("    \n");
      out.write(" \n");
      out.write("      <li class=\"dropdown\">\n");
      out.write("     <a href=\"javascript:void(0)\" class=\"dropa\">Sample Programs</a>\n");
      out.write("    <div class=\"dropdown-content\">\n");
      out.write("       <a href=\"csamples.html\">C</a>\n");
      out.write("      <a href=\"c++samples.html\">C++</a>\n");
      out.write("      <a href=\"javasamples.html\">JAVA</a>\n");
      out.write("    </div>\n");
      out.write("     <li><a href=\"helloworld.jsp\">Hello world</a></li>\n");
      out.write("     <li><a href=\"Prog-sites.html\">Top programming site</a></li>\n");
      out.write("     <li><a href=\"choosetest.html\">Take Test</a></li>\n");
      out.write("    <li><a href=\"aboutus.html\">About us</a></li>\n");
      out.write("     <li><a href=\"contactus.html\">Contact us</a></li>\n");
      out.write("     <li><a href=\"feedback.html\">Give Feedback</a></li>\n");
      out.write("          <li class=\"dropdown\">\n");
      out.write("     <a href=\"javascript:void(0)\" class=\"dropa\">Settings</a>\n");
      out.write("    <div class=\"dropdown-content\">\n");
      out.write("     <a href=\"changepassword.html\">Change Password</a>\n");
      out.write("     \n");
      out.write("    </div>\n");
      out.write("     <li><a href=\"Login.html\">Logout</a></li>\n");
      out.write("  </ul>\n");
      out.write("  <h2><u>Introduction To Computer Programming:</u></h2>\n");
      out.write("  <img src=\"cmp.jpg\" align=\"right\" width=\"500\" height=\"250\">\n");
      out.write("  <pre style=\"font-size:100%;\"><b><font face=\"sans-serif\">\n");
      out.write("Computer programming   </b>(often shortened to programming) is a process that leads from an original \n");
      out.write("formulation of a computing problem to executable computer programs. Programming involves activities such\n");
      out.write("as analysis, developing understanding, generating algorithms, verification of requirements of algorithms \n");
      out.write("including their correctness and resources consumption, and implementation (commonly referred to as \n");
      out.write("coding) of algorithms in a target programming language. Source code is written in one or more \n");
      out.write("programming languages. The purpose of programming is to find a sequence of instructions that will automate \n");
      out.write("performing a specific task or solving a given problem. The process of programming thus often requires \n");
      out.write("expertise in many different subjects, including knowledge of the application domain, specialized algorithms \n");
      out.write("and formal logic.\n");
      out.write("</pre>\n");
      out.write("<br></br>\n");
      out.write("  <body>\n");
      out.write(" <div align=\"left\"> <h2><u>The world's first computer programmer is a 200-year-old woman, and that's a great thing</u></h2></div>\n");
      out.write(" <div align=\"left\"><pre><font face=\"sans-serif\">\n");
      out.write(" <b>Ada Lovelace</b> has been called the world's first computer programmer. What she did was write \n");
      out.write(" the world's first machine algorithm for an early computing machine that existed only on paper. \n");
      out.write(" Of course, someone had to be the first, but Lovelace was a woman, and this was in the 1840s. \n");
      out.write(" Lovelace was a brilliant mathematician, thanks in part to opportunities that were denied most \n");
      out.write(" women of the time.\n");
      out.write(" </pre>\n");
      out.write(" </div>\n");
      out.write("<div align=\"center\"><img align=\"middle\" src=\"ada.jpg\" height=\"400\" width=\"400\"></div><br></br>\n");
      out.write("  </body>\n");
      out.write("  <body>\n");
      out.write(" <div align=\"left\"> <h2><u>The Most Popular Programming Languages of 2016 </u></h2></div><br></br>\n");
      out.write(" <div align=\"center\"><img src=\"ranking.png\" width=\"450\" height=\"350\"></div> \n");
      out.write("  </body><br></br>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
